export default {

  CLEAR_UNIT_RESOURCES: 'clearUnitResources',
  OPEN_CONFIRMATION_DIALOG: 'openConfirmationDialog',
  CLOSE_CONFIRMATION_DIALOG: 'closeConfirmationDialog',
  OPEN_ADD_RESOURCE_DIALOG: 'openAddResourceDialog',
  CLOSE_ADD_RESOURCE_DIALOG: 'closeAddResourceDialog',
  OPEN_VIEW_RESOURCE_DIALOG: 'openViewResourceDialog',
  CLOSE_VIEW_RESOURCE_DIALOG: 'closeViewResourceDialog',
  ADD_RESOURCE: 'addResource',
  WEBSOCKET_CONNECT: 'websocketConnect',
  WEBSOCKET_DISCONNECT: 'websocketDisconnect',
  WEBSOCKET_SUBSCRIBE: 'websocketSubscribe',
  WEBSOCKET_SEND: 'websocketSend',
  LOCK_UNIT: 'lockUnit',
  UNLOCK_UNIT: 'unlockUnit',
  INIT_UNITS: 'initUnits',
  UNIT_UPDATED: 'unitUpdated',
  CHANGE_ACTIVE_TAB: 'changeActiveTab',
};
