export default {
  CLEAR_UNIT_RESOURCES: "clearUnitResources",
  OPEN_CONFIRMATION_DIALOG: "openConfirmationDialog",
  CLOSE_CONFIRMATION_DIALOG: "closeConfirmationDialog",
  OPEN_VIEW_RESOURCE_DIALOG: "openViewResourceDialog",
  CLOSE_VIEW_RESOURCE_DIALOG: "closeViewResourceDialog",
  CLOSE_ADD_RESOURCE_DIALOG: "closeAddResourceDialog",
  ADD_RESOURCE: "addResource",
  WEBSOCKET_CONNECT: "websocketConnect",
  WEBSOCKET_DISCONNECT: "websocketDisconnect",
  WEBSOCKET_SUBSCRIBE: "websocketSubscribe",
  WEBSOCKET_UNSUBSCRIBE: "websocketUnsubscribe",
  WEBSOCKET_SUBSCRIBE_USER: "websocketSubscribeUser",
  WEBSOCKET_SEND: "websocketSend",
  LOCK_UNIT_RESPONSE_RECEIVED: "lockUnitResponseReceived",
  SHIFT_EXCHANGE_PENDING: "shiftExchangePending",
  UPDATE_RESOURCES_PENDING: "updateResourcesPending",
  LOCK_UNIT: "lockUnit",
  UNLOCK_UNIT: "unlockUnit",
  INIT_UNITS: "initUnits",
  UNIT_UPDATED: "unitUpdated",
  CHANGE_ACTIVE_TAB: "changeActiveTab",
  OPEN_STATUS_MENU: "openStatusMenu",
  CLOSE_STATUS_MENU: "closeStatusMenu",
  DELETE_RESOURCE: "deleteResource",
  UPDATE_RESOURCE: "updateResource",
  APPLY_RESOURCE_FILTER: "applyResourceFilter",
  SHOW_PDF_FILE: "showPdfFile",
  // Services section
  CHANGE_ACTIVE_TAB_SERVICES: "changeActiveTabServices",
  INIT_SERVICES: "initServices",
  APPLY_SERVICE_FILTER: "applyServiceFilter",
  CLEAR_ALL_SERVICES: "clearAllService",
  OPEN_DELETE_SERVICE_DIALOG: 'openDeleteServiceDialog',
  OPEN_EDIT_SERVICE_DIALOG: 'openEditServiceDialog',
  CLOSE_DELETE_SERVICE_DIALOG: 'closeDeleteServiceDialog',
  CLOSE_EDIT_SERVICE_DIALOG: 'closeEditServiceDialog',
  SET_SERVICE: 'setService',
 // Resource Management section
  SELECT_MANAGED_RESOURCE_TYPE: "selectManagedResourceType",
  SELECT_MANAGED_SUBUNIT: "selectManagedSubUnit",
  MANAGED_SUBUNITS_RECEIVED :"managedSubUnitsReceived",
  SELECT_MANAGED_FUNCTION: "selectManagedFunction",
  MANAGED_FUNCTIONS_RECEIVED: "managedFunctionsReceived",
  SELECT_MANAGED_VEHICLE_TYPE: "selectManagedVehicleType",
  MANAGED_VEHICLE_TYPES_RECEIVED: "managedVehicleTypesReceived",
  ADD_MANAGED_RESOURCE: "addManagedResource",
  DELETE_MANAGED_RESOURCE: "deleteManagedResource",
  SELECTED_RESOURCE_DATA_CHANGED:"changesUnsaved",
  CHANGES_SAVED:"changesSaved",
  CHANGES_REVERTED: "changesReverted",
  SHOW_UNSAVED_CHANGES_DIALOG: "showUnsavedChangesDialog",
  HIDE_UNSAVED_CHANGES_DIALOG: "hideUnsavedChangesDialog",
  MANAGEMENT_SUBUNIT_NAME_CHANGE: "managementSubunitNameChange",
  ADD_LOCATION: "addLocation",
  DELETE_LOCATION: "deleteLocation",
  AUTH_UPDATE_TOKEN: "authUpdateToken",
  AUTH_LOGOUT: "authLogout",
  AUTH_SET_USER_PROFILE: "authSetUserProfile",
  // LOCATIONS section
  INIT_LOCATIONS: "initLocations"
};
